### ISSUE TITLE
A s s e r t i o n   f a i l e d !

### ISSUE THREAD

**Issue by FedericoFedeFede** [CorentinJ/Real-Time-Voice-Cloning#705]
`python K:\cloning\Real-Time-Voice-Cloning-master\Real-Time-Voice-Cloning-master\demo_toolbox.py`

A s s e r t i o n   f a i l e d !

 P r o g r a m :   c : \ p y t h o n 3 8 \ p y t h o n . e x e
 F i l e :   s r c / h o s t a p i / w d m k s / p a _ w i n _ w d m k s . c ,   L i n e   1 0 8 1

 E x p r e s s i o n :   F A L S E

**Comment by FedericoFedeFede** [comment]
Solved with [python-sounddevice](https://anaconda.org/conda-forge/python-sounddevice)

**Comment by pacifist-dev** [comment]
to clarify, installing python-sounddevice fixed the issue or were there other steps involved? i have that package installed and still get the same error

**Comment by FedericoFedeFede** [comment]
I got no problem after that
